### ISSUE TITLE
“Close” button doesn’t work on Opera

### ISSUE THREAD

**Issue by Galixte** [david63/david63-cookiepolicy#1]
Hi @david63,

the “Close” button doesn’t work on Opera. It works on Chrome.

**Comment by david63** [comment]
What close button? There is no close button

**Comment by Galixte** [comment]
Yes there is a “Close” button: https://github.com/david63/david63-cookiepolicy/blob/master/david63/cookiepolicy/language/en/info_acp_cookiepolicy.php#L43 & https://github.com/david63/david63-cookiepolicy/blob/master/david63/cookiepolicy/adm/style/jscolor.js#L330. ;)
